name: Update from Oops
on:
  schedule:
    - cron: '0 0 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: true

    - name: Clone TxGVNN/oops
      uses: actions/checkout@v3
      with:
        repository: TxGVNN/oops
        fetch-depth: 1
        path: oops

    - name: Update dotfiles
      shell: bash
      run: |
        cp oops/profile/etc/emacs.d/init.el .emacs
        cp oops/profile/etc/screenrc .screenrc

    - name: Commit and push
      shell: bash
      run: |
        git diff --quiet && exit 0
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -u
        git commit -m "Update dotfiles (TxGVNN/oops)"
        git push -v origin HEAD\:refs/heads/master

